name: flutter_onboarding_app_task
description: "A Flutter app with onboarding, location, and alarm notifications"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  geolocator: ^10.1.0
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2
  intl:
  cupertino_icons: ^1.0.2
  flutter_local_notifications:
  geocoding: ^4.0.0
  timezone: ^0.9.4
  device_preview:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
